export const words = {
  Places: [
    { word: "Temple", similar: "Courtroom", hint: "Quiet rules apply" },
    { word: "Casino", similar: "Auction House", hint: "Risk meets money" },
    { word: "Prison", similar: "Boarding School", hint: "Restricted freedom" },
    { word: "Stadium", similar: "Concert Hall", hint: "Crowd energy zone" },
    { word: "Factory", similar: "Warehouse", hint: "Output over comfort" },
    { word: "Subway", similar: "Tunnel", hint: "Underground movement" },
    { word: "Hotel", similar: "Hostel", hint: "Temporary stay" },
    { word: "Zoo", similar: "Safari", hint: "Animals on display" },
    { word: "Court", similar: "Parliament", hint: "Decisions shape lives" },
    { word: "Mall", similar: "Bazaar", hint: "Money changes hands" },
    { word: "Bridge", similar: "Flyover", hint: "Above ground path" },
    { word: "Harbor", similar: "Dockyard", hint: "Water meets trade" },
    { word: "Lab", similar: "Workshop", hint: "Experiment zone" },
    { word: "Theater", similar: "Auditorium", hint: "Stage presence" },
    { word: "Gym", similar: "Arena", hint: "Physical grind" },
    { word: "Embassy", similar: "Consulate", hint: "Foreign soil indoors" },
    { word: "Farm", similar: "Plantation", hint: "Land earns food" },
    { word: "Station", similar: "Terminal", hint: "Departure point" },
    { word: "Fort", similar: "Castle", hint: "Old defense" },
    { word: "Island", similar: "Peninsula", hint: "Water surrounds?" },

  ],
  Movies: [
    { word: "Gladiator", similar: "Troy", hint: "Ancient conflict" },
    { word: "Joker", similar: "Venom", hint: "Villain focus" },
    { word: "Up", similar: "Coco", hint: "Emotional animation" },
    { word: "Gravity", similar: "Apollo 13", hint: "Space survival" },
    { word: "Parasite", similar: "Gone Girl", hint: "Dark deception" },
    { word: "Frozen II", similar: "Brave", hint: "Royal dilemma" },
    { word: "Avengers", similar: "Justice League", hint: "Team saves world" },
    { word: "Shrek", similar: "Kung Fu Panda", hint: "Green humor" },
    { word: "It", similar: "The Conjuring", hint: "Fear returns" },
    { word: "Cars", similar: "Turbo", hint: "Speed story" },
    { word: "Batman", similar: "Iron Man", hint: "Masked hero" },
    { word: "Dune", similar: "Star Wars", hint: "Desert destiny" },
    { word: "Rocky", similar: "Creed", hint: "Underdog rise" },
    { word: "Moana", similar: "Encanto", hint: "Island journey" },
    { word: "The Ring", similar: "Insidious", hint: "Supernatural threat" },
    { word: "Minions", similar: "Despicable Me", hint: "Yellow chaos" },
    { word: "Avatar 2", similar: "Aquaman", hint: "Water kingdom" },
    { word: "Hulk", similar: "Thor", hint: "Rage power" },
    { word: "Twilight", similar: "Underworld", hint: "Dark romance" },
    { word: "Matrix Reloaded", similar: "Tron", hint: "Digital reality" },

  ],
  Food: [
    { word: "Lasagna", similar: "Moussaka", hint: "Layered comfort" },
    { word: "Ramen", similar: "Pho", hint: "Broth matters" },
    { word: "Donut", similar: "Bagel", hint: "Round with hole" },
    { word: "Steak", similar: "Ribs", hint: "Grill centerpiece" },
    { word: "Sandwich", similar: "Wrap", hint: "Stuffed layers" },
    { word: "Biryani", similar: "Pulao", hint: "Spiced rice" },
    { word: "Pancake", similar: "Crepe", hint: "Flat sweet" },
    { word: "Curry", similar: "Stew", hint: "Thick gravy" },
    { word: "Brownie", similar: "Fudge", hint: "Dense chocolate" },
    { word: "Nachos", similar: "Popcorn", hint: "Snack share" },
    { word: "Omelette", similar: "Frittata", hint: "Egg form" },
    { word: "Hotdog", similar: "Sausage Roll", hint: "Street bite" },
    { word: "Falafel", similar: "Kebab", hint: "Middle eastern bite" },
    { word: "Dumpling", similar: "Gyoza", hint: "Filled pocket" },
    { word: "Risotto", similar: "Khichdi", hint: "Soft rice" },
    { word: "Tiramisu", similar: "Cheesecake", hint: "Layered dessert" },
    { word: "Samosa", similar: "Empanada", hint: "Stuffed pastry" },
    { word: "Pudding", similar: "Custard", hint: "Soft sweet" },
    { word: "Waffle", similar: "French Toast", hint: "Breakfast grid" },
    { word: "Churros", similar: "Pretzel", hint: "Fried twist" },

  ],
  Animals: [
    { word: "Wolf", similar: "Hyena", hint: "Pack hunter" },
    { word: "Panda", similar: "Koala", hint: "Cute but wild" },
    { word: "Cheetah", similar: "Leopard", hint: "Fast predator" },
    { word: "Shark", similar: "Barracuda", hint: "Ocean hunter" },
    { word: "Frog", similar: "Toad", hint: "Jumps and croaks" },
    { word: "Owl", similar: "Falcon", hint: "Night vision" },
    { word: "Camel", similar: "Llama", hint: "Desert adapted" },
    { word: "Penguin", similar: "Seal", hint: "Cold survivor" },
    { word: "Horse", similar: "Donkey", hint: "Hoofed worker" },
    { word: "Crocodile", similar: "Alligator", hint: "Ancient reptile" },
    { word: "Fox", similar: "Jackal", hint: "Clever survivor" },
    { word: "Gorilla", similar: "Chimpanzee", hint: "Power primate" },
    { word: "Peacock", similar: "Turkey", hint: "Feather show" },
    { word: "Deer", similar: "Moose", hint: "Forest grazer" },
    { word: "Octopus", similar: "Squid", hint: "Eight arms" },
    { word: "Bat", similar: "Flying Squirrel", hint: "Night glider" },
    { word: "Ant", similar: "Termite", hint: "Tiny colony" },
    { word: "Parrot", similar: "Macaw", hint: "Colorful talker" },
    { word: "Kangaroo", similar: "Wallaby", hint: "Pouch jumper" },
    { word: "Zebra", similar: "Horse", hint: "Striped grazer" },

  ],
  Sports: [
    { word: "Rugby", similar: "American Football", hint: "Oval ball chaos" },
    { word: "Baseball", similar: "Softball", hint: "Bat and bases" },
    { word: "Table Tennis", similar: "Squash", hint: "Small court speed" },
    { word: "Fencing", similar: "Kendo", hint: "Bladed duel" },
    { word: "Cycling", similar: "Skating", hint: "Balance race" },
    { word: "Karate", similar: "Taekwondo", hint: "Strike art" },
    { word: "Handball", similar: "Water Polo", hint: "Ball without feet" },
    { word: "Archery", similar: "Shooting", hint: "Target focus" },
    { word: "Skateboarding", similar: "Snowboarding", hint: "Board tricks" },
    { word: "Rowing", similar: "Kayaking", hint: "Water race" },
    { word: "Chess", similar: "Checkers", hint: "Mind battlefield" },
    { word: "Kabaddi", similar: "Kho Kho", hint: "Breath control game" },
    { word: "Surfing", similar: "Windsurfing", hint: "Wave rider" },
    { word: "Gymnastics", similar: "Parkour", hint: "Body control" },
    { word: "Ice Hockey", similar: "Field Hockey", hint: "Stick clash" },
    { word: "Formula 1", similar: "MotoGP", hint: "Speed circuit" },
    { word: "Skiing", similar: "Snowboarding", hint: "Snow descent" },
    { word: "Triathlon", similar: "Marathon", hint: "Endurance test" },
    { word: "Weightlifting", similar: "Powerlifting", hint: "Iron strength" },
    { word: "Billiards", similar: "Snooker", hint: "Cue precision" },
  ]
};

export const categories = Object.keys(words);
